preview/urls.py
from django.conf.urls import patterns, url, include

from preview import views

urlpatterns = patterns('', 
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.detail, name='detail'),
    url(r'^new/$', views.new, name='new'),
    url(r'^login/$', 'django.contrib.auth.views.login', 
        {'template_name': 'preview/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', 
        {'template_name': 'preview/logout.html'}, name='logout'),
    url(r'^reset/$', 'django.contrib.auth.views.password_reset', 
        {'template_name': 'preview/reset.html'}, name='reset'),
    url(r'^register/$', views.register, name='register'),
)

website/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'web.views.home', name='home'),
    # url(r'^web/', include('web.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^preview/admin/', include(admin.site.urls)),
    url(r'^preview/', include('preview.urls', namespace='preview'))
)

preview/models.py
from django.db import models
from django.contrib.auth.models import User


class Preview(models.Model):
    """ Preview information of an email. """

    sender = models.CharField(max_length=120)
    subject = models.CharField(max_length=120)
    body = models.CharField(max_length=480)
    date = models.DateTimeField() # date created by creator.
    creator = models.ForeignKey(User)

    def __unicode__(self):
        return self.subject


class Comment(models.Model):
    """ Stores comments on a preview. """
    
    preview = models.ForeignKey(Preview)
    comment = models.CharField(max_length=480)
    date = models.DateTimeField()
    commentor = models.ForeignKey(User)

    def __unicode__(self):
        return self.comment

preview/views.py
from django.views import generic
from django.forms import ModelForm, Textarea
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

from preview.models import Preview, Comment


# for login_required decorator
login_url = '/preview/login'

class PreviewForm(ModelForm):
    """ Use for creating/editing email previews."""
    class Meta:
        model = Preview
        fields = ['sender', 'subject', 'body']

class CommentForm(ModelForm):
    """ For adding comments to a Preview."""
    
    class Meta:
        model = Comment
        fields = ['comment']
        widgets = {
            'comment': Textarea,
        }


class IndexView(generic.ListView):
    """ Main view for existing previews."""

    template_name = 'preview/index.html'
    context_object_name = 'email_list'

    def get_queryset(self):
        return Preview.objects.all().order_by('-date')


@login_required(login_url=login_url)
def detail(request, pk):
    """ View of a Preview and associated comments. Accepts new comments."""

    preview = get_object_or_404(Preview, pk=pk)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # don't commit until we've set up the non-user input fields
            new_comment = comment_form.save(commit=False)
            new_comment.date = timezone.now()
            new_comment.preview = preview
            new_comment.commentor = request.user
            # add user information too? ... depends on auth system?
            new_comment.save()
            
            return HttpResponseRedirect(reverse('preview:detail', 
                                                kwargs={'pk': pk}))
    else:
        comment_form = CommentForm()

    comments = Comment.objects.filter(preview=preview)
    context = {
        'preview_object': preview,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'preview/detail.html', context)


@login_required(login_url=login_url)
def new(request):
    """ Form fields for creating/editing a Preview db entry. """
    
    if request.method == 'POST':
        # fill
        form = PreviewForm(request.POST)
        if form.is_valid():
            new_preview = form.save(commit=False)
            new_preview.creator = request.user
            new_preview.date = timezone.now()
            new_preview.save()
            # --> created preview
            return HttpResponseRedirect(reverse('preview:detail', 
                kwargs={'pk': new_preview.id}))
    else:
        # empty form
        form = PreviewForm()

    return render(request, 'preview/new.html', {'form': form})


def register(request):
    """ Form for registering a new User."""

    if request.method == 'POST':
        user_form = UserCreationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save()
            # login the user
            user = authenticate(username=request.POST['username'], 
                                password=request.POST['password1'])
            if user is not None:
                login(request, user)
            # else error - but that should never happen
            return HttpResponseRedirect(reverse('preview:index')) 
    else:
        user_form = UserCreationForm()

    return render(request, 'preview/register.html', {'form': user_form})

preview/templates/preview/base.html
<!DOCTYPE html>

<head>
{% block head %}
{% block header_content %} 

{% endblock %}
<link rel="stylesheet" type="text/css" href="/static/preview/preview.css">
{% endblock %}
</head>

<body>
{% block page_header %}
<ul id="page-title-block">
  <li id="title"><a href={% url 'preview:index' %}><span>Gmail Preview</span></a></li>
 {% if user.is_authenticated %}
  <li class="nav"><a href={% url 'preview:new' %}>New</a></li>
  <li class="nav"><a href={% url 'preview:logout' %}>Logout</a></li>
  {% else %}
  <li class="nav"><a href={% url 'preview:login' %}>Login</a></li>
  {% endif %}
</ul>

<div id="content">
  {% endblock %}

  {% block content %}
</div>

{% endblock %}

{% block page_footer %}
<div id="page-footer-block">  
 
</div>
{% endblock %}
</body>

preview/templates/preview/detail.html
{% extends "preview/base.html" %}

{% block header_content %}
{% include "preview/gmail_inbox_header.html" %}
{% endblock %}

{% block content %}

  <div id="preview">
    {% include "preview/gmail_inbox_body.html" %}
  </div>

  <div id="comments">
    <ul>
    {% if comments %}
      {% for comment in comments %}
      <li>
        <div class="comment-body">{{ comment.comment }}</div>
        <div class="comment-details"> 
          <span class="user">{{ comment.commentor }}</span> 
          <span class="time">at {{ comment.date|date:"g:i a" }} on {{ comment.date|date:"F j" }}</span>
        </div>
      </li>
      {% endfor %}

      {% else %}
      <li><div class="comment-body">There are no comments on this post.</div></li>
      {% endif %}
    </ul>

    <form action={% url 'preview:detail' preview_object.id %} method="post">
      {% csrf_token %}
      {{ comment_form.as_p }}
      <input type="submit" value="Comment">
    </form>

  </div>
{% endblock %}

preview/templates/preview/index.html
{% extends "preview/base.html" %}

{% block content %}
<div id="preview-explanation" class="basic-content-margins">
  <p> A tool for checking how the subject line and message body of an email will appear in the Gmail inbox. <a class="inline-link"href={% url 'preview:login' %}>Login</a> to create new emails, check out previews created by other users, and leave comments.
</p>
<h2>Recent Previews:</h2>
</div>
{% if email_list %}
    <ul id="index-list">
    {% for email in email_list %}
    <li><a href={% url 'preview:detail' email.pk %}><span class="subject">{{ email.subject }}</span><span class="body">{{ email.body }}</span></a>
      <span class="creator">Created by <em>{{ email.creator }}</em></span></li> 
    {% endfor %}
    </ul>

{% else %}
    No previews here.
{% endif %}

{% endblock %}

preview/templates/preview/login.html
{% extends "preview/base.html" %}

{% block content %}
<div id="login" class="basic-content-margins">
  <form method="post" action="{% url 'preview:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
    <input type="hidden" name="next" value="{{ next }}">
  </form>

  <p>Don't have a username? Click <a class="inline-link" href={% url 'preview:register' %}>here</a> to register.<p>
</div>
 
{% endblock %}

preview/templates/preview/logout.html
{% extends "preview/base.html" %} 

{% block content %}
<div id="logged-out" class="basic-content-margins">
  <p>You have been logged out.</p>
  <p>Click <a class="inline-link" href={% url 'preview:index' %}>here</a> to return to the home page, or <a class="inline-link" href={% url 'preview:login' %}>login</a> again.</p>
</div>
{% endblock %}

preview/templates/preview/new.html
{% extends "preview/base.html" %}

{% block content %}
<div id="new" class="basic-content-margins"> 

  <div id="new-form-description">
    <h3>New Preview</h3>
    <p>Use this form to create a sample email for your previewing pleasure.</p>
  </div>

  <div id="new-form">
    <form action={% url 'preview:new' %} method="post"> 
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Preview">
    </form>
  </div>

</div>
{% endblock %}

preview/templates/preview/register.html
{% extends "preview/base.html" %}

{% block content %}

<div id="registration-form" class="basic-content-margins">
  <form action={% url 'preview:register' %} method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
  </form>
</div>
                                                   
{% endblock %}